# Site settings
author: Elias Ventura
title: Between The Lines
header-img: img/home-bg.png
email: eliasventura23@gmail.com
copyright_name: Elias Ventura
description: > # this means to ignore newlines until "baseurl:"
  One Line At a Time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  destro1234

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
